export const MOCK_SYSTEM_DESIGN = [
  "# System Design: vercel/next.js",
  "",
  "## 1. Overview",
  "",
  "Next.js is a full-stack React framework built for production. It provides a complete solution for building web applications — from static site generation to dynamic server-side rendering and edge computing. The architecture is designed for maximal performance and developer experience.",
  "",
  "```",
  "                    ┌─────────────────────────────────────────┐",
  "                    │          Browser / Client               │",
  "                    │  ┌──────────┐    ┌────────────────────┐ │",
  "                    │  │ RSC Tree │    │  Client Components │ │",
  "                    │  │(no JS)   │    │  (hydrated)        │ │",
  "                    │  └──────────┘    └────────────────────┘ │",
  "                    └─────────────────┬───────────────────────┘",
  "                                      │ HTTP / WebSocket",
  "                    ┌─────────────────▼───────────────────────┐",
  "                    │          Next.js Server                  │",
  "                    │  ┌──────────────┐  ┌───────────────┐   │",
  "                    │  │  App Router  │  │ Pages Router  │   │",
  "                    │  │  (RSC+SSR)   │  │   (legacy)    │   │",
  "                    │  └──────┬───────┘  └───────┬───────┘   │",
  "                    │         │                   │            │",
  "                    │  ┌──────▼───────────────────▼───────┐  │",
  "                    │  │         Route Handler             │  │",
  "                    │  │  (middleware → render → stream)   │  │",
  "                    │  └────────────────┬──────────────────┘  │",
  "                    └───────────────────┼─────────────────────┘",
  "                                        │",
  "                    ┌───────────────────▼─────────────────────┐",
  "                    │           Data Layer                     │",
  "                    │  Database  │  Cache  │  External APIs    │",
  "                    └──────────────────────────────────────────┘",
  "```",
  "",
  "---",
  "",
  "## 2. Core Subsystems",
  "",
  "### 2.1 App Router (React Server Components)",
  "",
  "The App Router is built on React's Server Component architecture. Every component in the `app/` directory is a Server Component by default — it renders on the server and sends zero JavaScript to the client.",
  "",
  "```",
  "Request → Middleware → Route Resolution → RSC Render → HTML Stream → Client",
  "                                              │",
  "                                    ┌─────────▼──────────┐",
  "                                    │  Component Tree     │",
  "                                    │  ├── Layout (SC)    │",
  "                                    │  ├── Page (SC)      │",
  "                                    │  │   ├── Header (SC)│",
  "                                    │  │   └── Button (CC)│← \"use client\"",
  "                                    │  └── Footer (SC)    │",
  "                                    └────────────────────┘",
  "```",
  "",
  "### 2.2 Build System",
  "",
  "Next.js uses a hybrid build system depending on the environment:",
  "",
  "| Environment | Bundler | Transpiler |",
  "|-------------|---------|------------|",
  "| Production build | Webpack 5 | SWC (Rust) |",
  "| Development (default) | Webpack 5 | SWC (Rust) |",
  "| Development (--turbo) | Turbopack | SWC (Rust) |",
  "",
  "Turbopack is written in Rust and uses incremental computation (inspired by Salsa) for sub-100ms HMR.",
  "",
  "### 2.3 Rendering Strategies",
  "",
  "Next.js supports four rendering modes, automatically selected based on component code:",
  "",
  "1. **Static (SSG)** — pre-rendered at build time, served from CDN",
  "2. **Incremental Static Regeneration (ISR)** — static but with on-demand revalidation",
  "3. **Server-Side Rendering (SSR)** — rendered per-request on the server",
  "4. **Client-Side Rendering (CSR)** — rendered in the browser via `\"use client\"`",
  "",
  "---",
  "",
  "## 3. Data Flow Architecture",
  "",
  "```",
  "Browser",
  "  │",
  "  ├── Navigation Event (Link click)",
  "  │     │",
  "  │     ▼",
  "  │   Router (client)",
  "  │     │  prefetch()",
  "  │     ▼",
  "  │   RSC Payload Cache (in-memory)",
  "  │     │  HIT → render from cache",
  "  │     │  MISS → fetch from server",
  "  │",
  "  └── Server Action (form/button)",
  "        │",
  "        ▼",
  "      Server Action Handler",
  "        │  validateInput()",
  "        │  await db.mutate()",
  "        │  revalidatePath()",
  "        ▼",
  "      Cache Invalidation → Re-render → Stream to client",
  "```",
  "",
  "---",
  "",
  "## 4. Middleware Architecture",
  "",
  "Middleware runs at the Edge before the request reaches the server:",
  "",
  "```",
  "CDN Edge Node",
  "  │",
  "  ▼",
  "middleware.ts (runs in Edge Runtime)",
  "  │  ├── Authentication check",
  "  │  ├── A/B testing / feature flags",
  "  │  ├── Geolocation-based routing",
  "  │  └── Rate limiting",
  "  │",
  "  ▼",
  "Next.js Server (Node.js / Edge)",
  "  │",
  "  ▼",
  "Route Handler / Page",
  "```",
  "",
  "Edge middleware has access to `NextRequest`, `NextResponse`, and Web APIs but NOT Node.js APIs.",
  "",
  "---",
  "",
  "## 5. Image Optimization Pipeline",
  "",
  "```",
  "<Image src=\"/photo.jpg\" width={800} height={600} />",
  "        │",
  "        ▼",
  "    /_next/image?url=/photo.jpg&w=800&q=75",
  "        │",
  "        ▼",
  "    Image Optimization Server",
  "        │  ├── Format detection (WebP, AVIF)",
  "        │  ├── Size optimization",
  "        │  ├── CDN cache headers",
  "        │  └── Blur placeholder generation",
  "        ▼",
  "    Optimized image response (cached 1 year)",
  "```",
  "",
  "---",
  "",
  "## 6. Caching Strategy",
  "",
  "Next.js implements a 4-layer caching system:",
  "",
  "| Layer | Location | Duration | Revalidation |",
  "|-------|----------|----------|--------------|",
  "| Request Memoization | Per-request memory | Request lifetime | Automatic |",
  "| Data Cache | Server-side persistent | Configurable | `revalidatePath` / `revalidateTag` |",
  "| Full Route Cache | Server-side (CDN) | Build-time static | On-demand / ISR |",
  "| Router Cache | Client-side memory | Session | Navigation |",
  "",
  "---",
  "",
  "## 7. Deployment Architecture",
  "",
  "```",
  "GitHub",
  "  │",
  "  ▼",
  "Vercel CI/CD",
  "  │  ├── `next build` (webpack + SWC)",
  "  │  ├── Static assets → Global CDN",
  "  │  ├── Server Functions → Serverless (Node.js)",
  "  │  └── Edge Middleware → Edge Network (100+ regions)",
  "  │",
  "  ▼",
  "Production",
  "  ├── Static Assets (CDN, ~3ms TTFB)",
  "  ├── RSC/SSR Pages (Serverless, ~50-200ms TTFB)",
  "  └── Edge Routes (Edge Runtime, ~10-30ms TTFB)",
  "```",
  "",
  "---",
  "",
  "## 8. Security Architecture",
  "",
  "- **CSP Headers**: Next.js generates Content Security Policy headers automatically for strict-dynamic scripts",
  "- **CSRF**: Prevented via SameSite cookies + Origin header validation in Server Actions",
  "- **XSS**: React's JSX escaping prevents reflected XSS by default",
  "- **Secret Management**: `NEXT_PUBLIC_*` vars are public; all others are server-only",
  "",
  "---",
  "",
  "## 9. Monorepo Structure",
  "",
  "```",
  "next.js/",
  "├── packages/",
  "│   ├── next/          ← Core framework (the npm package)",
  "│   ├── font/          ← next/font implementation",
  "│   ├── image/         ← Standalone image optimizer",
  "│   └── third-parties/ ← next/third-parties helpers",
  "├── examples/          ← 100+ starter examples",
  "├── test/              ← E2E and unit tests",
  "├── docs/              ← MDX documentation source",
  "└── turbo.json         ← Turborepo pipeline config",
  "```",
  "",
  "---",
  "",
  "## 10. Performance Characteristics",
  "",
  "| Metric | Value | Notes |",
  "|--------|-------|-------|",
  "| Cold start (Serverless) | ~50ms | With Streaming SSR |",
  "| HMR (Turbopack) | <100ms | Via incremental computation |",
  "| HMR (Webpack) | 200-800ms | Depends on module graph size |",
  "| First Contentful Paint | <1s | With RSC + streaming |",
  "| Static page TTFB | ~3ms | CDN-cached |",
  "| Bundle size (base) | ~72KB | First-load JS, gzipped |",
].join("\n");
