import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "CodebaseGPT Terms of Service.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-24">
      <h1 className="text-3xl font-bold text-[#111114] mb-2" style={{ fontFamily: "var(--font-display)" }}>Terms of Service</h1>
      <p className="text-sm text-[#5B5F66] mb-10">Last updated: July 2026</p>
      <div className="prose-gitplus space-y-6">
        <p>By accessing or using CodebaseGPT (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you disagree, do not use the Service.</p>

        <h2>1. Description of Service</h2>
        <p>CodebaseGPT provides AI-powered tools for analyzing, searching, and understanding GitHub repositories. The Service includes repository indexing, code chat, security scanning, and document generation.</p>

        <h2>2. Acceptable Use</h2>
        <p>You agree to use the Service only for lawful purposes and in compliance with these Terms. You must not:</p>
        <ul>
          <li>Use the Service to analyze repositories you do not have permission to access.</li>
          <li>Attempt to reverse engineer, disassemble, or decompile the Service.</li>
          <li>Submit malicious code or attempt to exploit the Service infrastructure.</li>
          <li>Use the Service in any way that violates applicable laws or regulations.</li>
        </ul>

        <h2>3. Intellectual Property</h2>
        <p>You retain all rights to your code and data. We do not claim any ownership or intellectual property rights over the code you submit for analysis.</p>

        <h2>4. AI-Generated Content</h2>
        <p>Content generated by the AI (security findings, architecture documents, chat responses) is provided &quot;as is&quot; and should not be considered authoritative. Always verify AI suggestions with human review before implementing them in production systems.</p>

        <h2>5. Limitation of Liability</h2>
        <p>The Service is provided &quot;as is&quot; without warranties of any kind. We shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>

        <h2>6. Changes to Terms</h2>
        <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the modified Terms.</p>

        <h2>7. Contact</h2>
        <p>Questions about these Terms should be directed to legal@codebasegpt.dev.</p>
      </div>
    </div>
  );
}
