import { useState, useRef } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { ChevronLeft, Code2, FileDown, Loader2, LayoutDashboard } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useRepoStore } from "@/lib/store";
import { generateSystemDesign } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";
import ReactMarkdown from "react-markdown";
import jsPDF from "jspdf";

const SystemDesign = () => {
  const { repoId } = useParams();
  const navigate = useNavigate();
  const { meta, repoContext } = useRepoStore();
  const { toast } = useToast();
  const [content, setContent] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasGenerated, setHasGenerated] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const generate = async () => {
    if (!repoContext) {
      toast({ title: "No repo data", description: "Please index a repository first.", variant: "destructive" });
      return;
    }
    setIsGenerating(true);
    try {
      const result = await generateSystemDesign(repoContext);
      setContent(result);
      setHasGenerated(true);
    } catch (e: any) {
      toast({ title: "Generation failed", description: e.message, variant: "destructive" });
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadPDF = () => {
    if (!content) return;
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 15;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    const addText = (text: string, size: number, bold = false, color: [number, number, number] = [30, 30, 30]) => {
      doc.setFontSize(size);
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text, maxWidth);
      for (const line of lines) {
        if (y > 275) { doc.addPage(); y = 20; }
        doc.text(line, margin, y);
        y += size * 0.45;
      }
      y += 2;
    };

    addText(`System Design: ${meta?.owner}/${meta?.name}`, 18, true, [20, 20, 20]);
    y += 4;
    addText(`Generated by GitPlus`, 9, false, [120, 120, 120]);
    y += 8;

    for (const line of content.split("\n")) {
      if (line.startsWith("# ")) { y += 6; addText(line.slice(2), 16, true); }
      else if (line.startsWith("## ")) { y += 4; addText(line.slice(3), 13, true, [40, 40, 40]); }
      else if (line.startsWith("### ")) { y += 2; addText(line.slice(4), 11, true, [60, 60, 60]); }
      else if (line.startsWith("```")) { /* skip */ }
      else if (line.startsWith("- ")) { addText(`  • ${line.slice(2)}`, 9); }
      else if (line.trim()) { addText(line, 9); }
      else { y += 3; }
    }

    doc.save(`system-design-${meta?.name || "document"}.pdf`);
    toast({ title: "PDF downloaded" });
  };

  return (
    <div className="min-h-screen bg-background">
      <nav className="sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-sm">
        <div className="max-w-4xl mx-auto flex items-center justify-between h-11 px-6">
          <div className="flex items-center gap-2">
            <button onClick={() => navigate(`/repo/${repoId}`)} className="text-muted-foreground hover:text-foreground transition-colors">
              <ChevronLeft className="h-4 w-4" />
            </button>
            <Code2 className="h-3.5 w-3.5 text-primary" />
            <span className="text-[11px] text-muted-foreground">
              {meta?.owner}/<span className="text-foreground font-medium">{meta?.name}</span>
              <span className="text-muted-foreground"> / system-design</span>
            </span>
          </div>
          <div className="flex items-center gap-1.5">
            {hasGenerated && (
              <Button onClick={downloadPDF} size="sm" className="h-7 text-[11px]">
                <FileDown className="h-3 w-3 mr-1" /> PDF
              </Button>
            )}
            <Button onClick={generate} disabled={isGenerating} size="sm" variant="outline" className="h-7 text-[11px]">
              {isGenerating ? <Loader2 className="h-3 w-3 mr-1 animate-spin" /> : <LayoutDashboard className="h-3 w-3 mr-1" />}
              {isGenerating ? "Generating..." : hasGenerated ? "Regenerate" : "Generate"}
            </Button>
          </div>
        </div>
      </nav>

      <div className="max-w-4xl mx-auto px-6 py-6">
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }}>
          {!hasGenerated && !isGenerating && (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <LayoutDashboard className="h-10 w-10 text-muted-foreground/20 mb-3" />
              <p className="text-sm text-muted-foreground mb-3">Generate a system design document from this codebase.</p>
              <Button onClick={generate} size="sm" className="text-xs">
                <LayoutDashboard className="h-3 w-3 mr-1.5" /> Generate
              </Button>
            </div>
          )}

          {isGenerating && (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <Loader2 className="h-8 w-8 text-primary animate-spin mb-3" />
              <p className="text-sm text-muted-foreground">Analyzing architecture...</p>
            </div>
          )}

          {hasGenerated && !isGenerating && (
            <div ref={contentRef} className="prose prose-invert prose-sm max-w-none
              [&_h1]:text-base [&_h1]:font-semibold [&_h1]:text-foreground [&_h1]:border-b [&_h1]:border-border [&_h1]:pb-2 [&_h1]:mb-4
              [&_h2]:text-sm [&_h2]:font-medium [&_h2]:text-foreground [&_h2]:mt-6 [&_h2]:mb-2
              [&_h3]:text-xs [&_h3]:font-medium [&_h3]:text-muted-foreground [&_h3]:uppercase [&_h3]:tracking-wider
              [&_p]:text-sm [&_p]:text-secondary-foreground [&_p]:leading-relaxed
              [&_ul]:text-sm [&_ul]:text-secondary-foreground
              [&_li]:text-sm
              [&_code]:text-xs [&_code]:bg-muted [&_code]:px-1 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-primary
              [&_pre]:bg-card [&_pre]:border [&_pre]:border-border [&_pre]:rounded [&_pre]:p-3
              [&_pre_code]:bg-transparent [&_pre_code]:p-0
              [&_strong]:text-foreground
              [&_table]:border-collapse [&_th]:border [&_th]:border-border [&_th]:px-3 [&_th]:py-1.5 [&_th]:text-xs [&_th]:bg-muted
              [&_td]:border [&_td]:border-border [&_td]:px-3 [&_td]:py-1.5 [&_td]:text-xs
            ">
              <ReactMarkdown>{content}</ReactMarkdown>
            </div>
          )}
        </motion.div>
      </div>
    </div>
  );
};

export default SystemDesign;
